apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-config
  namespace: rd-microservices
data:
  application.yml: |
    server:
      port: 8085
    jwt:
      secret: oK9V1Yv7fF2lX5JgH8KzQ3dP+S1R0wYuL2d7Aq3ZkF4=
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-config
  namespace: rd-microservices
data:
  application.yml: |
    server:
      port: 8081
    jwt:
      secret: oK9V1Yv7fF2lX5JgH8KzQ3dP+S1R0wYuL2d7Aq3ZkF4=
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: project-config
  namespace: rd-microservices
data:
  application.yml: |
    server:
      port: 8082
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: validation-config
  namespace: rd-microservices
data:
  application.yml: |
    server:
      port: 8083
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: finance-config
  namespace: rd-microservices
data:
  application.yml: |
    server:
      port: 8084

