apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
  namespace: rd-microservices
type: Opaque
stringData:
  jwt-secret: "oK9V1Yv7fF2lX5JgH8KzQ3dP+S1R0wYuL2d7Aq3ZkF4="
---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-secret
  namespace: rd-microservices
type: Opaque
stringData:
  admin-password: "admin123"
  db-password: "keycloak_password"
---
apiVersion: v1
kind: Secret
metadata:
  name: grafana-secret
  namespace: rd-microservices
type: Opaque
stringData:
  admin-password: "admin123"
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-auth-secret
  namespace: rd-microservices
type: Opaque
stringData:
  username: "postgres"
  password: "bifo2004"
  database: "auth_db"
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-project-secret
  namespace: rd-microservices
type: Opaque
stringData:
  username: "postgres"
  password: "bifo2004"
  database: "project_db"
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-validation-secret
  namespace: rd-microservices
type: Opaque
stringData:
  username: "postgres"
  password: "bifo2004"
  database: "validation_db"
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-finance-secret
  namespace: rd-microservices
type: Opaque
stringData:
  username: "postgres"
  password: "bifo2004"
  database: "finance_db"
