apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
  namespace: rd-microservices
type: Opaque
stringData:
  jwt-secret: "your-256-bit-secret-key-change-in-production-minimum-32-characters"
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-auth-secret
  namespace: rd-microservices
type: Opaque
stringData:
  username: auth_user
  password: auth_password
  database: auth_db
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-project-secret
  namespace: rd-microservices
type: Opaque
stringData:
  username: project_user
  password: project_password
  database: project_db
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-validation-secret
  namespace: rd-microservices
type: Opaque
stringData:
  username: validation_user
  password: validation_password
  database: validation_db
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-finance-secret
  namespace: rd-microservices
type: Opaque
stringData:
  username: finance_user
  password: finance_password
  database: finance_db

